steps:
 - name: 'gcr.io/cloud-builders/dotnet'
   args: ['restore','--packages', '/packages']
   timeout: 500s
 - name: 'gcr.io/cloud-builders/dotnet'
   args: ['build','-c','Release']
   timeout: 500s