//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeaveYourCouch.Mvc.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveYourCouch is developped and maintained by only one person. The website and the data are hosted in a Google Cloud Platform Virtual Machine. The monthly fees for this hosting (not including domain name registration) and the use of the various Google api is about 80€ without traffic..
        /// </summary>
        public static string about_content_01 {
            get {
                return ResourceManager.GetString("about_content_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Your Couch.
        /// </summary>
        public static string appname {
            get {
                return ResourceManager.GetString("appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string event_create_address {
            get {
                return ResourceManager.GetString("event_create_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string event_create_date {
            get {
                return ResourceManager.GetString("event_create_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string event_create_description {
            get {
                return ResourceManager.GetString("event_create_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting details.
        /// </summary>
        public static string event_create_meeting_point {
            get {
                return ResourceManager.GetString("event_create_meeting_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string event_create_participants {
            get {
                return ResourceManager.GetString("event_create_participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Event.
        /// </summary>
        public static string event_create_private {
            get {
                return ResourceManager.GetString("event_create_private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string event_create_time {
            get {
                return ResourceManager.GetString("event_create_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ttile.
        /// </summary>
        public static string event_create_title {
            get {
                return ResourceManager.GetString("event_create_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new event.
        /// </summary>
        public static string event_index_createnew {
            get {
                return ResourceManager.GetString("event_index_createnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string event_index_tabular_date {
            get {
                return ResourceManager.GetString("event_index_tabular_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string event_index_tabular_owner {
            get {
                return ResourceManager.GetString("event_index_tabular_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participants.
        /// </summary>
        public static string event_index_tabular_participants {
            get {
                return ResourceManager.GetString("event_index_tabular_participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string event_index_tabular_time {
            get {
                return ResourceManager.GetString("event_index_tabular_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string event_index_tabular_title {
            get {
                return ResourceManager.GetString("event_index_tabular_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize events. Meet people. Make new friends..
        /// </summary>
        public static string jumbohome {
            get {
                return ResourceManager.GetString("jumbohome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free..
        /// </summary>
        public static string jumbohome_sub {
            get {
                return ResourceManager.GetString("jumbohome_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No adds. .
        /// </summary>
        public static string jumbohome_sub1 {
            get {
                return ResourceManager.GetString("jumbohome_sub1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-devices..
        /// </summary>
        public static string jumbohome_sub2 {
            get {
                return ResourceManager.GetString("jumbohome_sub2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string nav_link_about {
            get {
                return ResourceManager.GetString("nav_link_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string nav_link_contact {
            get {
                return ResourceManager.GetString("nav_link_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string nav_link_events {
            get {
                return ResourceManager.GetString("nav_link_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string nav_link_home {
            get {
                return ResourceManager.GetString("nav_link_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string nav_login {
            get {
                return ResourceManager.GetString("nav_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string nav_logoff {
            get {
                return ResourceManager.GetString("nav_logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string nav_register {
            get {
                return ResourceManager.GetString("nav_register", resourceCulture);
            }
        }
    }
}
